spring:
  application:
    name: user-center-backend
    # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mdo
    username: root
    password: root
server:
  port: 8080
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false